/**
 * Created by zhaojp on 2016/10/8.
 */
export const FETCH_MERGE_PATH = 'FETCH_MERGE_PATH';
export const FETCH_MERGE_PATH_PENDING = 'FETCH_MERGE_PATH_PENDING';
export const FETCH_MERGE_PATH_SUCCESS = 'FETCH_MERGE_PATH_SUCCESS';
export const FETCH_MERGE_PATH_ERROR = 'FETCH_MERGE_PATH_ERROR';


export const FETCH_ISSUES_DATA = 'FETCH_ISSUES_DATA';
export const FETCH_ISSUES_DATA_PENDING = 'FETCH_ISSUES_DATA_PENDING';
export const FETCH_ISSUES_DATA_SUCCESS = 'FETCH_ISSUES_DATA_SUCCESS';
export const FETCH_ISSUES_DATA_ERROR = 'FETCH_ISSUES_DATA_ERROR';

export const CREATE_MR = 'CREATE_MR';
export const CREATE_MR_PENDING = 'CREATE_MR_PENDING';
export const CREATE_MR_SUCCESS = 'CREATE_MR_SUCCESS';
export const CREATE_MR_ERROR = 'CREATE_MR_ERROR';

export const FETCH_MR_LIST = 'FETCH_MR_LIST';
export const FETCH_MR_LIST_PENDING = 'FETCH_MR_LIST_PENDING';
export const FETCH_MR_LIST_SUCCESS = 'FETCH_MR_LIST_SUCCESS';
export const FETCH_MR_LIST_ERROR = 'FETCH_MR_LIST_ERROR';

export const GET_MR_CODE_CHANGES = 'GET_MR_CODE_CHANGES';
export const GET_MR_CODE_CHANGES_PENDING = 'GET_MR_CODE_CHANGES_PENDING';
export const GET_MR_CODE_CHANGES_SUCCESS = 'GET_MR_CODE_CHANGES_SUCCESS';
export const GET_MR_CODE_CHANGES_ERROR = 'GET_MR_CODE_CHANGES_ERROR';
