/**
 * Created by zhaojp on 2016/11/28.
 */
export const GET_CONFIRM_LIST = 'GET_CONFIRM_LIST';
export const GET_CONFIRM_LIST_PENDING = 'GET_CONFIRM_LIST_PENDING';
export const GET_CONFIRM_LIST_SUCCESS = 'GET_CONFIRM_LIST_SUCCESS';
export const GET_CONFIRM_LIST_ERROR = 'GET_CONFIRM_LIST_ERROR';

export const GET_TRANSPOND_MEMBER = 'GET_TRANSPOND_MEMBER';
export const GET_TRANSPOND_MEMBER_PENDING = 'GET_TRANSPOND_MEMBER_PENDING';
export const GET_TRANSPOND_MEMBER_SUCCESS = 'GET_TRANSPOND_MEMBER_SUCCESS';
export const GET_TRANSPOND_MEMBER_ERROR = 'GET_TRANSPOND_MEMBER_ERROR';

export const DEVELOP_TRANSPOND = 'DEVELOP_TRANSPOND';
export const DEVELOP_TRANSPOND_PENDING = 'DEVELOP_TRANSPOND_PENDING';
export const DEVELOP_TRANSPOND_SUCCESS = 'DEVELOP_TRANSPOND_SUCCESS';
export const DEVELOP_TRANSPOND_ERROR = 'DEVELOP_TRANSPOND_ERROR';

export const GET_MY_PROJECT_INFO = 'GET_MY_PROJECT_INFO';
export const GET_MY_PROJECT_INFO_PENDING = 'GET_MY_PROJECT_INFO_PENDING';
export const GET_MY_PROJECT_INFO_SUCCESS = 'GET_MY_PROJECT_INFO_SUCCESS';
export const GET_MY_PROJECT_INFO_ERROR = 'GET_MY_PROJECT_INFO_ERROR';

export const DEVELOP_CONFIRM = 'DEVELOP_CONFIRM';
export const DEVELOP_CONFIRM_PENDING = 'DEVELOP_CONFIRM_PENDING';
export const DEVELOP_CONFIRM_SUCCESS = 'DEVELOP_CONFIRM_SUCCESS';
export const DEVELOP_CONFIRM_ERROR = 'DEVELOP_CONFIRM_ERROR';