/**
 * Created by Administrator on 2017/4/17.
 */
export const GET_BACKLOG_NODE = 'GET_BACKLOG_NODE';
export const GET_BACKLOG_NODE_PENDING = 'GET_BACKLOG_NODE_PENDING';
export const GET_BACKLOG_NODE_SUCCESS = 'GET_BACKLOG_NODE_SUCCESS';
export const GET_BACKLOG_NODE_ERROR = 'GET_BACKLOG_NODE_ERROR';

export const ADD_BACKLOG_NODE = 'ADD_BACKLOG_NODE';
export const ADD_BACKLOG_NODE_PENDING = 'ADD_BACKLOG_NODE_PENDING';
export const ADD_BACKLOG_NODE_SUCCESS = 'ADD_BACKLOG_NODE_SUCCESS';
export const ADD_BACKLOG_NODE_ERROR = 'ADD_BACKLOG_NODE_ERROR';

export const MODIFY_BACKLOG_NODE = 'MODIFY_BACKLOG_NODE';
export const MODIFY_BACKLOG_NODE_PENDING = 'MODIFY_BACKLOG_NODE_PENDING';
export const MODIFY_BACKLOG_NODE_SUCCESS = 'MODIFY_BACKLOG_NODE_SUCCESS';
export const MODIFY_BACKLOG_NODE_ERROR = 'MODIFY_BACKLOG_NODE_ERROR';

export const DELETE_BACKLOG_NODE = 'DELETE_BACKLOG_NODE';
export const DELETE_BACKLOG_NODE_PENDING = 'DELETE_BACKLOG_NODE_PENDING';
export const DELETE_BACKLOG_NODE_SUCCESS = 'DELETE_BACKLOG_NODE_SUCCESS';
export const DELETE_BACKLOG_NODE_ERROR = 'DELETE_BACKLOG_NODE_ERROR';