/**
 * Created by zhaojp on 2016/10/11.
 */
export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const FETCH_BRANCHES_PENDING = 'FETCH_BRANCHES_PENDING';
export const FETCH_BRANCHES_SUCCESS = 'FETCH_BRANCHES_SUCCESS';
export const FETCH_BRANCHES_ERROR = 'FETCH_BRANCHES_ERROR';

export const CREATE_BRANCHES = 'CREATE_BRANCHES';
export const CREATE_BRANCHES_PENDING = 'CREATE_BRANCHES_PENDING';
export const CREATE_BRANCHES_SUCCESS = 'CREATE_BRANCHES_SUCCESS';
export const CREATE_BRANCHES_ERROR = 'CREATE_BRANCHES_ERROR';