/**
 * Created by zhaojp on 2017/1/3.
 */

export const PUSH_CODE_TO_MASTER = 'PUSH_CODE_TO_MASTER';
export const PUSH_CODE_TO_MASTER_PENDING = 'PUSH_CODE_TO_MASTER_PENDING';
export const PUSH_CODE_TO_MASTER_SUCCESS = 'PUSH_CODE_TO_MASTER_SUCCESS';
export const PUSH_CODE_TO_MASTER_ERROR = 'PUSH_CODE_TO_MASTER_ERROR';

export const PUSH_CODE_TO_RELEASE = 'PUSH_CODE_TO_RELEASE';
export const PUSH_CODE_TO_RELEASE_PENDING = 'PUSH_CODE_TO_RELEASE_PENDING';
export const PUSH_CODE_TO_RELEASE_SUCCESS = 'PUSH_CODE_TO_RELEASE_SUCCESS';
export const PUSH_CODE_TO_RELEASE_ERROR = 'PUSH_CODE_TO_RELEASE_ERROR';