/**
 * Created by helen on 2016/9/19.
 */
module.exports.assign ={
    "success": true,
    "errorCode": null,
    "errorMsg": null,
    "result": {
        "milestones": [
            {
                "id": 118,
                "iid": 94,
                "title": "测试",
                "description": "设置开始时间",
                "state": "active",
                "project_id": 17,
                "due_date": 1477180800000,
                "updated_date": null,
                "created_date": null
            },
            {
                "id": 105,
                "iid": 85,
                "title": "sdfaa",
                "description": "sdfa",
                "state": "active",
                "project_id": 17,
                "due_date": 1477353600000,
                "updated_date": null,
                "created_date": null
            },
            {
                "id": 101,
                "iid": 81,
                "title": "dsafgs",
                "description": "sdf",
                "state": "active",
                "project_id": 17,
                "due_date": 1477353600000,
                "updated_date": null,
                "created_date": null
            },
            {
                "id": 100,
                "iid": 80,
                "title": "dsafg",
                "description": "sdf",
                "state": "active",
                "project_id": 17,
                "due_date": 1477353600000,
                "updated_date": null,
                "created_date": null
            },
            {
                "id": 96,
                "iid": 76,
                "title": "as",
                "description": "as",
                "state": "active",
                "project_id": 17,
                "due_date": 1477353600000,
                "updated_date": null,
                "created_date": null
            }
        ],
        "labels": [
            {
                "name": "接口设计",
                "color": "#428bca"
            },
            {
                "name": "测试label",
                "color": "#69d100"
            }
        ],
        "members": [
            {
                "avatarUrl": "http://www.gravatar.com/avatar/0e6353ce63402966aeb25fd19decd72a?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "liurq",
                "provider": null,
                "name": "刘仁权",
                "id": 15,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/0e6353ce63402966aeb25fd19decd72a?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null,
                "access_level": "Developer"
            },
            {
                "avatarUrl": "http://www.gravatar.com/avatar/ba0584c0cdb61625fcdc5cc380370e1e?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "zhaojp",
                "provider": null,
                "name": "赵婧萍",
                "id": 10,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/ba0584c0cdb61625fcdc5cc380370e1e?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null,
                "access_level": "Master"
            },
            {
                "avatarUrl": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "sunlei",
                "provider": null,
                "name": "孙磊",
                "id": 9,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null,
                "access_level": "Reporter"
            },
            {
                "avatarUrl": "http://10.10.152.146:10080/uploads/user/avatar/8/avatar.png",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "digimonster",
                "provider": null,
                "name": "张亚军",
                "id": 8,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://10.10.152.146:10080/uploads/user/avatar/8/avatar.png",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null,
                "access_level": "Master"
            }
        ]
    }
};


module.exports.notes={
    "success": true,
    "errorCode": null,
    "errorMsg": null,
    "result": [
        {
            "id": 231,
            "body": "Status changed to closed",
            "attachment": null,
            "author": {
                "avatarUrl": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "sunlei",
                "provider": null,
                "name": "孙磊",
                "id": 9,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null
            },
            "system": true,
            "upvote": false,
            "downvote": false,
            "created_at": 1476092193000
        },
        {
            "id": 232,
            "body": "Status changed to reopened",
            "attachment": null,
            "author": {
                "avatarUrl": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "sunlei",
                "provider": null,
                "name": "孙磊",
                "id": 9,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null
            },
            "system": true,
            "upvote": false,
            "downvote": false,
            "created_at": 1476092343000
        },
        {
            "id": 308,
            "body": "Status changed to closed",
            "attachment": null,
            "author": {
                "avatarUrl": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "sunlei",
                "provider": null,
                "name": "孙磊",
                "id": 9,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null
            },
            "system": true,
            "upvote": false,
            "downvote": false,
            "created_at": 1476254143000
        },
        {
            "id": 309,
            "body": "issue dis",
            "attachment": null,
            "author": {
                "avatarUrl": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "admin": false,
                "blocked": false,
                "bio": null,
                "skype": null,
                "linkedin": null,
                "twitter": null,
                "darkScheme": false,
                "themeId": null,
                "externUid": null,
                "externProviderName": null,
                "websiteUrl": null,
                "canCreateGroup": false,
                "canCreateProject": false,
                "canCreateTeam": false,
                "colorSchemeId": null,
                "privateToken": null,
                "projectsLimit": null,
                "username": "sunlei",
                "provider": null,
                "name": "孙磊",
                "id": 9,
                "state": "active",
                "currentSignInAt": null,
                "lastSignInAt": null,
                "email": null,
                "createdAt": null,
                "private_token": null,
                "color_scheme_id": null,
                "website_url": null,
                "created_at": null,
                "dark_scheme": false,
                "theme_id": null,
                "extern_uid": null,
                "is_admin": false,
                "can_create_group": false,
                "can_create_project": false,
                "can_create_team": false,
                "avatar_url": "http://www.gravatar.com/avatar/0201c34545ee15888d7effb255fdf3c4?s=80&d=identicon",
                "last_sign_in_at": null,
                "current_sign_in_at": null,
                "projects_limit": null
            },
            "system": false,
            "upvote": false,
            "downvote": false,
            "created_at": 1476254285000
        }
    ]
};
