/**
 * Created by zhaojp on 2016/10/8.
 */
export const FETCH_NAMESPACE = 'FETCH_NAMESPACE';
export const FETCH_NAMESPACE_PENDING = 'FETCH_NAMESPACE_PENDING';
export const FETCH_NAMESPACE_SUCCESS = 'FETCH_NAMESPACE_SUCCESS';
export const FETCH_NAMESPACE_ERROR = 'FETCH_NAMESPACE_ERROR';


export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';