/**
 * Created by zhaojp on 2016/10/8.
 */
export const FETCH_TARGET_PROJECT = 'FETCH_TARGET_PROJECT';
export const FETCH_TARGET_PROJECT_PENDING = 'FETCH_TARGET_PROJECT_PENDING';
export const FETCH_TARGET_PROJECT_SUCCESS = 'FETCH_TARGET_PROJECT_SUCCESS';
export const FETCH_TARGET_PROJECT_ERROR = 'FETCH_TARGET_PROJECT_ERROR';


export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const FETCH_ISSUES_DATA = 'FETCH_ISSUES_DATA';
export const FETCH_ISSUES_DATA_PENDING = 'FETCH_ISSUES_DATA_PENDING';
export const FETCH_ISSUES_DATA_SUCCESS = 'FETCH_ISSUES_DATA_SUCCESS';
export const FETCH_ISSUES_DATA_ERROR = 'FETCH_ISSUES_DATA_ERROR';

export const CREATE_MR = 'CREATE_MR';
export const CREATE_MR_PENDING = 'CREATE_MR_PENDING';
export const CREATE_MR_SUCCESS = 'CREATE_MR_SUCCESS';
export const CREATE_MR_ERROR = 'CREATE_MR_ERROR';

export const REVERT_MR = 'REVERT_MR';
export const REVERT_MR_PENDING = 'REVERT_MR_PENDING';
export const REVERT_MR_SUCCESS = 'REVERT_MR_SUCCESS';
export const REVERT_MR_ERROR = 'REVERT_MR_ERROR';

export const FETCH_MR_LIST = 'FETCH_MR_LIST';
export const FETCH_MR_LIST_PENDING = 'FETCH_MR_LIST_PENDING';
export const FETCH_MR_LIST_SUCCESS = 'FETCH_MR_LIST_SUCCESS';
export const FETCH_MR_LIST_ERROR = 'FETCH_MR_LIST_ERROR';

