/**
 * Created by Administrator on 2016-09-23.
 */
export const ACQUIRE_MYGROUP = 'ACQUIRE_MYGROUP';
export const ACQUIRE_MYGROUP_PENDING = 'ACQUIRE_MYGROUP_PENDING';
export const ACQUIRE_MYGROUP_SUCCESS = 'ACQUIRE_MYGROUP_SUCCESS';
export const ACQUIRE_MYGROUP_ERROR = 'ACQUIRE_MYGROUP_ERROR';