/**
 * Created by Administrator on 2016-09-23.
 */
export const GET_GROUPMEMBERS = 'GET_GROUPMEMBERS';
export const GET_GROUPMEMBERS_PENDING = 'GET_GROUPMEMBERS_PENDING';
export const GET_GROUPMEMBERS_SUCCESS = 'GET_GROUPMEMBERS_SUCCESS';
export const GET_GROUPMEMBERS_ERROR = 'GET_GROUPMEMBERS_ERROR';